from collections.abc import Mapping, Sequence

BASES = ("Curitiba", "Macaé", "Ipatinga", "Camaçari", "São Luís")

ROLE_CATALOG: Mapping[str, Sequence[str]] = {
    "Engenharia": (
        "Engenheiro Mecânico",
        "Engenheiro Civil",
        "Engenheiro Elétrico",
        "Engenheiro de Instrumentação",
        "Engenheiro de Tubulação",
        "Engenheiro de Processos",
        "Engenheiro de Segurança",
        "Engenheiro de Materiais",
        "Engenheiro de Planejamento",
        "Projetista Mecânico",
        "Projetista de Tubulação",
        "Desenhista Técnico",
    ),
    "Projetos": (
        "Gerente de Projetos",
        "Coordenador de Projetos",
        "Líder de Disciplina",
        "Analista de Projetos",
        "Controlador de Documentos",
        "Administrador de Contratos",
        "Analista de Medição",
        "Assistente de Projetos",
    ),
    "Planejamento": (
        "Gerente de Planejamento",
        "Coordenador de Planejamento",
        "Planejador de Obras",
        "Planejador de Manutenção",
        "Analista de Planejamento",
        "Controlador de Custos",
        "Analista de Riscos",
        "Apontador de Produção",
    ),
    "Suprimentos": (
        "Gerente de Suprimentos",
        "Coordenador de Suprimentos",
        "Comprador Técnico",
        "Comprador de Serviços",
        "Analista de Suprimentos",
        "Analista de Contratos",
        "Inspetor de Suprimentos",
        "Assistente de Compras",
    ),
    "Qualidade": (
        "Gerente da Qualidade",
        "Coordenador da Qualidade",
        "Engenheiro da Qualidade",
        "Inspetor de Soldagem",
        "Inspetor Dimensional",
        "Inspetor de Pintura",
        "Técnico da Qualidade",
    ),
    "Saúde, Segurança e Meio Ambiente": (
        "Gerente de SMS",
        "Coordenador de SMS",
        "Técnico de Segurança do Trabalho",
        "Técnico de Meio Ambiente",
        "Higienista Ocupacional",
        "Enfermeiro do Trabalho",
        "Técnico de Enfermagem do Trabalho",
        "Bombeiro Civil",
    ),
    "Operações": (
        "Gerente de Operações",
        "Coordenador de Operações",
        "Supervisor de Montagem",
        "Encarregado de Montagem",
        "Caldeireiro",
        "Soldador",
        "Montador de Andaime",
        "Rigger",
        "Operador de Guindaste",
        "Operador de Plataforma Elevatória",
        "Ajudante de Produção",
        "Isolador Térmico",
    ),
    "Manutenção": (
        "Gerente de Manutenção",
        "Coordenador de Manutenção",
        "Supervisor de Manutenção",
        "Mecânico de Manutenção",
        "Eletricista de Manutenção",
        "Instrumentista",
        "Lubrificador Industrial",
        "Técnico de Confiabilidade",
    ),
    "Logística": (
        "Gerente de Logística",
        "Coordenador de Logística",
        "Analista de Logística",
        "Almoxarife",
        "Operador de Empilhadeira",
        "Motorista de Veículo Pesado",
    ),
    "Administrativo e Financeiro": (
        "Gerente Administrativo Financeiro",
        "Analista Financeiro",
        "Analista Fiscal",
        "Analista Contábil",
        "Assistente Administrativo",
        "Auxiliar de Serviços Gerais",
    ),
    "Pessoas": (
        "Gerente de Pessoas",
        "Business Partner de Pessoas",
        "Analista de Desenvolvimento Humano",
        "Analista de Administração de Pessoal",
    ),
    "Tecnologia": (
        "Gerente de Tecnologia",
        "Analista de Sistemas",
        "Técnico de Suporte",
    ),
}

QUALIFICATION_NAMES = (
    "NR-01 Disposições Gerais",
    "NR-05 CIPA",
    "NR-06 Equipamento de Proteção Individual",
    "NR-07 Programa de Controle Médico",
    "NR-10 Segurança em Eletricidade",
    "NR-11 Movimentação de Materiais",
    "NR-12 Segurança em Máquinas",
    "NR-13 Caldeiras e Vasos de Pressão",
    "NR-18 Segurança na Construção",
    "NR-20 Segurança com Inflamáveis",
    "NR-23 Proteção Contra Incêndios",
    "NR-26 Sinalização de Segurança",
    "NR-33 Espaço Confinado - Trabalhador",
    "NR-33 Espaço Confinado - Vigia",
    "NR-33 Espaço Confinado - Supervisor",
    "NR-34 Trabalho a Quente",
    "NR-35 Trabalho em Altura",
    "Primeiros Socorros",
    "Brigada de Emergência",
    "Permissão de Trabalho",
    "Soldagem Eletrodo Revestido",
    "Soldagem MIG/MAG",
    "Soldagem TIG",
    "Soldagem Arame Tubular",
    "Soldagem Oxiacetilênica",
    "Qualificação de Soldador 6G",
    "Qualificação de Soldador ASME IX",
    "Qualificação de Soldador AWS D1.1",
    "Soldagem de Aço Inoxidável",
    "Soldagem de Alumínio",
    "Tratamento Térmico de Solda",
    "Simbologia de Soldagem",
    "Inspeção Visual de Solda",
    "Líquido Penetrante Nível 1",
    "Líquido Penetrante Nível 2",
    "Partícula Magnética Nível 1",
    "Partícula Magnética Nível 2",
    "Ultrassom Nível 1",
    "Ultrassom Nível 2",
    "Radiografia Industrial Nível 1",
    "Radiografia Industrial Nível 2",
    "Inspeção Dimensional",
    "Operação de Empilhadeira",
    "Operação de Guindaste",
    "Operação de Ponte Rolante",
    "Operação de Plataforma Elevatória",
    "Movimentação de Cargas",
    "Sinaleiro e Rigger",
    "Montagem de Andaime",
    "Direção Defensiva",
    "Operação de Munck",
    "Operação de Talha",
    "Leitura e Interpretação de Desenho",
    "Metrologia Industrial",
    "Controle Dimensional",
    "Pintura Industrial",
    "Isolamento Térmico",
    "Torqueamento Controlado",
    "Alinhamento de Máquinas",
    "Balanceamento de Máquinas",
    "Gestão da Qualidade ISO 9001",
    "Gestão Ambiental ISO 14001",
    "Gestão de Segurança ISO 45001",
    "Auditor Interno de Sistemas",
    "Planejamento com Primavera P6",
    "Planejamento com Microsoft Project",
    "Gestão de Projetos",
    "Gestão de Riscos",
    "Liderança Operacional",
    "Excel para Análise de Dados",
    "Power BI Operacional",
    "Segurança da Informação",
)

AUTHORIZATION_NAMES = (
    "Acesso a Área Industrial",
    "Acesso a Área Classificada",
    "Acesso a Subestação",
    "Acesso a Espaço Confinado",
    "Emissão de Permissão de Trabalho",
    "Liberação de Trabalho a Quente",
    "Bloqueio e Etiquetagem",
    "Condução de Veículo Leve",
    "Condução de Veículo Pesado",
    "Operação de Empilhadeira",
    "Operação de Guindaste",
    "Operação de Plataforma Elevatória",
    "Operação de Ponte Rolante",
    "Operação de Munck",
    "Supervisão de Entrada",
    "Vigia de Espaço Confinado",
    "Trabalho em Altura",
    "Inspeção de Soldagem",
    "Inspeção de Pintura",
    "Inspeção Dimensional",
    "Responsável por Área",
    "Responsável Técnico",
    "Aprovação de Medição",
    "Administração de Contrato",
)
