from collections.abc import Mapping, Sequence

BASES = ("Curitiba", "Maca�", "Ipatinga", "Cama�ari", "S�o Lu�s")

ROLE_CATALOG: Mapping[str, Sequence[str]] = {
    "Engenharia": (
        "Engenheiro Mec�nico",
        "Engenheiro Civil",
        "Engenheiro El�trico",
        "Engenheiro de Instrumenta��o",
        "Engenheiro de Tubula��o",
        "Engenheiro de Processos",
        "Engenheiro de Seguran�a",
        "Engenheiro de Materiais",
        "Engenheiro de Planejamento",
        "Projetista Mec�nico",
        "Projetista de Tubula��o",
        "Desenhista T�cnico",
    ),
    "Projetos": (
        "Gerente de Projetos",
        "Coordenador de Projetos",
        "L�der de Disciplina",
        "Analista de Projetos",
        "Controlador de Documentos",
        "Administrador de Contratos",
        "Analista de Medi��o",
        "Assistente de Projetos",
    ),
    "Planejamento": (
        "Gerente de Planejamento",
        "Coordenador de Planejamento",
        "Planejador de Obras",
        "Planejador de Manuten��o",
        "Analista de Planejamento",
        "Controlador de Custos",
        "Analista de Riscos",
        "Apontador de Produ��o",
    ),
    "Suprimentos": (
        "Gerente de Suprimentos",
        "Coordenador de Suprimentos",
        "Comprador T�cnico",
        "Comprador de Servi�os",
        "Analista de Suprimentos",
        "Analista de Contratos",
        "Inspetor de Suprimentos",
        "Assistente de Compras",
    ),
    "Qualidade": (
        "Gerente da Qualidade",
        "Coordenador da Qualidade",
        "Engenheiro da Qualidade",
        "Inspetor de Soldagem",
        "Inspetor Dimensional",
        "Inspetor de Pintura",
        "T�cnico da Qualidade",
    ),
    "Sa�de, Seguran�a e Meio Ambiente": (
        "Gerente de SMS",
        "Coordenador de SMS",
        "T�cnico de Seguran�a do Trabalho",
        "T�cnico de Meio Ambiente",
        "Higienista Ocupacional",
        "Enfermeiro do Trabalho",
        "T�cnico de Enfermagem do Trabalho",
        "Bombeiro Civil",
    ),
    "Opera��es": (
        "Gerente de Opera��es",
        "Coordenador de Opera��es",
        "Supervisor de Montagem",
        "Encarregado de Montagem",
        "Caldeireiro",
        "Soldador",
        "Montador de Andaime",
        "Rigger",
        "Operador de Guindaste",
        "Operador de Plataforma Elevat�ria",
        "Ajudante de Produ��o",
        "Isolador T�rmico",
    ),
    "Manuten��o": (
        "Gerente de Manuten��o",
        "Coordenador de Manuten��o",
        "Supervisor de Manuten��o",
        "Mec�nico de Manuten��o",
        "Eletricista de Manuten��o",
        "Instrumentista",
        "Lubrificador Industrial",
        "T�cnico de Confiabilidade",
    ),
    "Log�stica": (
        "Gerente de Log�stica",
        "Coordenador de Log�stica",
        "Analista de Log�stica",
        "Almoxarife",
        "Operador de Empilhadeira",
        "Motorista de Ve�culo Pesado",
    ),
    "Administrativo e Financeiro": (
        "Gerente Administrativo Financeiro",
        "Analista Financeiro",
        "Analista Fiscal",
        "Analista Cont�bil",
        "Assistente Administrativo",
        "Auxiliar de Servi�os Gerais",
    ),
    "Pessoas": (
        "Gerente de Pessoas",
        "Business Partner de Pessoas",
        "Analista de Desenvolvimento Humano",
        "Analista de Administra��o de Pessoal",
    ),
    "Tecnologia": (
        "Gerente de Tecnologia",
        "Analista de Sistemas",
        "T�cnico de Suporte",
    ),
}

QUALIFICATION_NAMES = (
    "NR-01 Disposi��es Gerais",
    "NR-05 CIPA",
    "NR-06 Equipamento de Prote��o Individual",
    "NR-07 Programa de Controle M�dico",
    "NR-10 Seguran�a em Eletricidade",
    "NR-11 Movimenta��o de Materiais",
    "NR-12 Seguran�a em M�quinas",
    "NR-13 Caldeiras e Vasos de Press�o",
    "NR-18 Seguran�a na Constru��o",
    "NR-20 Seguran�a com Inflam�veis",
    "NR-23 Prote��o Contra Inc�ndios",
    "NR-26 Sinaliza��o de Seguran�a",
    "NR-33 Espa�o Confinado - Trabalhador",
    "NR-33 Espa�o Confinado - Vigia",
    "NR-33 Espa�o Confinado - Supervisor",
    "NR-34 Trabalho a Quente",
    "NR-35 Trabalho em Altura",
    "Primeiros Socorros",
    "Brigada de Emerg�ncia",
    "Permiss�o de Trabalho",
    "Soldagem Eletrodo Revestido",
    "Soldagem MIG/MAG",
    "Soldagem TIG",
    "Soldagem Arame Tubular",
    "Soldagem Oxiacetil�nica",
    "Qualifica��o de Soldador 6G",
    "Qualifica��o de Soldador ASME IX",
    "Qualifica��o de Soldador AWS D1.1",
    "Soldagem de A�o Inoxid�vel",
    "Soldagem de Alum�nio",
    "Tratamento T�rmico de Solda",
    "Simbologia de Soldagem",
    "Inspe��o Visual de Solda",
    "L�quido Penetrante N�vel 1",
    "L�quido Penetrante N�vel 2",
    "Part�cula Magn�tica N�vel 1",
    "Part�cula Magn�tica N�vel 2",
    "Ultrassom N�vel 1",
    "Ultrassom N�vel 2",
    "Radiografia Industrial N�vel 1",
    "Radiografia Industrial N�vel 2",
    "Inspe��o Dimensional",
    "Opera��o de Empilhadeira",
    "Opera��o de Guindaste",
    "Opera��o de Ponte Rolante",
    "Opera��o de Plataforma Elevat�ria",
    "Movimenta��o de Cargas",
    "Sinaleiro e Rigger",
    "Montagem de Andaime",
    "Dire��o Defensiva",
    "Opera��o de Munck",
    "Opera��o de Talha",
    "Leitura e Interpreta��o de Desenho",
    "Metrologia Industrial",
    "Controle Dimensional",
    "Pintura Industrial",
    "Isolamento T�rmico",
    "Torqueamento Controlado",
    "Alinhamento de M�quinas",
    "Balanceamento de M�quinas",
    "Gest�o da Qualidade ISO 9001",
    "Gest�o Ambiental ISO 14001",
    "Gest�o de Seguran�a ISO 45001",
    "Auditor Interno de Sistemas",
    "Planejamento com Primavera P6",
    "Planejamento com Microsoft Project",
    "Gest�o de Projetos",
    "Gest�o de Riscos",
    "Lideran�a Operacional",
    "Excel para An�lise de Dados",
    "Power BI Operacional",
    "Seguran�a da Informa��o",
)

AUTHORIZATION_NAMES = (
    "Acesso a �rea Industrial",
    "Acesso a �rea Classificada",
    "Acesso a Subesta��o",
    "Acesso a Espa�o Confinado",
    "Emiss�o de Permiss�o de Trabalho",
    "Libera��o de Trabalho a Quente",
    "Bloqueio e Etiquetagem",
    "Condu��o de Ve�culo Leve",
    "Condu��o de Ve�culo Pesado",
    "Opera��o de Empilhadeira",
    "Opera��o de Guindaste",
    "Opera��o de Plataforma Elevat�ria",
    "Opera��o de Ponte Rolante",
    "Opera��o de Munck",
    "Supervis�o de Entrada",
    "Vigia de Espa�o Confinado",
    "Trabalho em Altura",
    "Inspe��o de Soldagem",
    "Inspe��o de Pintura",
    "Inspe��o Dimensional",
    "Respons�vel por �rea",
    "Respons�vel T�cnico",
    "Aprova��o de Medi��o",
    "Administra��o de Contrato",
)
