"""core schema

Revision ID: 0001_core_schema
Revises:
Create Date: 2026-08-11 15:07:30.860040
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_core_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.String(length=120), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_aggregate",
        "audit_events",
        ["aggregate_type", "aggregate_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "app_users",
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_users")),
        sa.UniqueConstraint("email", name=op.f("uq_app_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_app_users_username")),
    )
    op.create_index(
        "ix_app_users_active_role",
        "app_users",
        ["active", "role"],
        unique=False,
    )
    op.create_table(
        "authorizations",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("scope_type", sa.String(length=48), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authorizations")),
        sa.UniqueConstraint("code", name=op.f("uq_authorizations_code")),
    )
    op.create_table(
        "calibration_parameters",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("rationale", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calibration_parameters")),
    )
    op.create_index(
        "ix_calibration_parameters_name_version",
        "calibration_parameters",
        ["name", "version"],
        unique=True,
    )
    op.create_table(
        "operational_restrictions",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("hard_constraint", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operational_restrictions")),
        sa.UniqueConstraint("code", name=op.f("uq_operational_restrictions_code")),
    )
    op.create_table(
        "operations",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("client_name", sa.String(length=180), nullable=False),
        sa.Column("base_location", sa.String(length=80), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("budget_cents", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_operations_valid_period")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
        sa.UniqueConstraint("code", name=op.f("uq_operations_code")),
    )
    op.create_index(
        op.f("ix_operations_base_location"), "operations", ["base_location"], unique=False
    )
    op.create_index(
        "ix_operations_period_status",
        "operations",
        ["starts_at", "ends_at", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_operations_status"), "operations", ["status"], unique=False)
    op.create_table(
        "qualifications",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=80), nullable=True),
        sa.Column("level", sa.String(length=48), nullable=True),
        sa.Column("validity_days", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qualifications")),
        sa.UniqueConstraint("code", name=op.f("uq_qualifications_code")),
    )
    op.create_index(
        op.f("ix_qualifications_category"), "qualifications", ["category"], unique=False
    )
    op.create_table(
        "role_families",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_families")),
        sa.UniqueConstraint("code", name=op.f("uq_role_families_code")),
        sa.UniqueConstraint("name", name=op.f("uq_role_families_name")),
    )
    op.create_table(
        "technical_competencies",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("scale_max", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technical_competencies")),
        sa.UniqueConstraint("code", name=op.f("uq_technical_competencies_code")),
    )
    op.create_table(
        "decision_runs",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("objective", sa.String(length=48), nullable=False),
        sa.Column("solver_version", sa.String(length=40), nullable=False),
        sa.Column("rules_version", sa.String(length=40), nullable=False),
        sa.Column("input_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("runtime_ms", sa.Integer(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_decision_runs_operation_id_operations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_runs")),
    )
    op.create_index(
        op.f("ix_decision_runs_input_snapshot_hash"),
        "decision_runs",
        ["input_snapshot_hash"],
        unique=False,
    )
    op.create_index(
        "ix_decision_runs_operation_created",
        "decision_runs",
        ["operation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "eligibility_runs",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("rules_version", sa.String(length=40), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_eligibility_runs_operation_id_operations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility_runs")),
    )
    op.create_index(
        op.f("ix_eligibility_runs_input_hash"), "eligibility_runs", ["input_hash"], unique=False
    )
    op.create_index(
        op.f("ix_eligibility_runs_operation_id"), "eligibility_runs", ["operation_id"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"], ["role_families.id"], name=op.f("fk_roles_family_id_role_families")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_index("ix_roles_active_family", "roles", ["active", "family_id"], unique=False)
    op.create_table(
        "training_catalog",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("qualification_id", sa.Uuid(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("cost_cents", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["qualifications.id"],
            name=op.f("fk_training_catalog_qualification_id_qualifications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_catalog")),
        sa.UniqueConstraint("code", name=op.f("uq_training_catalog_code")),
    )
    op.create_table(
        "decision_outcomes",
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("outcome_metrics", sa.JSON(), nullable=False),
        sa.Column("recorded_by", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_id"],
            ["decision_runs.id"],
            name=op.f("fk_decision_outcomes_decision_run_id_decision_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_outcomes")),
        sa.UniqueConstraint("decision_run_id", name=op.f("uq_decision_outcomes_decision_run_id")),
    )
    op.create_table(
        "employees",
        sa.Column("employee_number", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("canonical_role_id", sa.Uuid(), nullable=False),
        sa.Column("base_location", sa.String(length=80), nullable=False),
        sa.Column("seniority_level", sa.String(length=40), nullable=False),
        sa.Column("hired_on", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_role_id"], ["roles.id"], name=op.f("fk_employees_canonical_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint("email", name=op.f("uq_employees_email")),
        sa.UniqueConstraint("employee_number", name=op.f("uq_employees_employee_number")),
    )
    op.create_index(
        "ix_employees_active_role", "employees", ["active", "canonical_role_id"], unique=False
    )
    op.create_index(
        "ix_employees_base_active", "employees", ["base_location", "active"], unique=False
    )
    op.create_index(op.f("ix_employees_name"), "employees", ["name"], unique=False)
    op.create_table(
        "operation_role_demands",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("shift_code", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_operation_role_demands_positive_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_operation_role_demands_operation_id_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_operation_role_demands_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_role_demands")),
        sa.UniqueConstraint("operation_id", "role_id", "shift_code", name="role_shift"),
    )
    op.create_index(
        op.f("ix_operation_role_demands_operation_id"),
        "operation_role_demands",
        ["operation_id"],
        unique=False,
    )
    op.create_table(
        "role_aliases",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("source_title", sa.String(length=200), nullable=False),
        sa.Column("normalized_title", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_aliases_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_aliases")),
        sa.UniqueConstraint("normalized_title", name=op.f("uq_role_aliases_normalized_title")),
    )
    op.create_index(op.f("ix_role_aliases_role_id"), "role_aliases", ["role_id"], unique=False)
    op.create_table(
        "training_sessions",
        sa.Column("training_catalog_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("base_location", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_training_sessions_valid_period")),
        sa.ForeignKeyConstraint(
            ["training_catalog_id"],
            ["training_catalog.id"],
            name=op.f("fk_training_sessions_training_catalog_id_training_catalog"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_sessions")),
    )
    op.create_table(
        "decision_assignments",
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("role_demand_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("incremental_cost_cents", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_id"],
            ["decision_runs.id"],
            name=op.f("fk_decision_assignments_decision_run_id_decision_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_decision_assignments_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["role_demand_id"],
            ["operation_role_demands.id"],
            name=op.f("fk_decision_assignments_role_demand_id_operation_role_demands"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_assignments")),
    )
    op.create_index(
        op.f("ix_decision_assignments_decision_run_id"),
        "decision_assignments",
        ["decision_run_id"],
        unique=False,
    )
    op.create_table(
        "decision_training_actions",
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("training_catalog_id", sa.Uuid(), nullable=False),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cost_cents", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_id"],
            ["decision_runs.id"],
            name=op.f("fk_decision_training_actions_decision_run_id_decision_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_decision_training_actions_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["training_catalog_id"],
            ["training_catalog.id"],
            name=op.f("fk_decision_training_actions_training_catalog_id_training_catalog"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_training_actions")),
    )
    op.create_index(
        op.f("ix_decision_training_actions_decision_run_id"),
        "decision_training_actions",
        ["decision_run_id"],
        unique=False,
    )
    op.create_table(
        "eligibility_results",
        sa.Column("eligibility_run_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("role_demand_id", sa.Uuid(), nullable=False),
        sa.Column("classification", sa.String(length=24), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("gaps", sa.JSON(), nullable=False),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("incremental_cost_cents", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["eligibility_run_id"],
            ["eligibility_runs.id"],
            name=op.f("fk_eligibility_results_eligibility_run_id_eligibility_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_eligibility_results_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["role_demand_id"],
            ["operation_role_demands.id"],
            name=op.f("fk_eligibility_results_role_demand_id_operation_role_demands"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility_results")),
        sa.UniqueConstraint(
            "eligibility_run_id", "employee_id", "role_demand_id", name="run_candidate"
        ),
    )
    op.create_index(
        "ix_eligibility_results_classification",
        "eligibility_results",
        ["eligibility_run_id", "classification"],
        unique=False,
    )
    op.create_table(
        "employee_assignments",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_employee_assignments_valid_period")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_assignments_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_employee_assignments_operation_id_operations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_assignments")),
    )
    op.create_index(
        op.f("ix_employee_assignments_operation_id"),
        "employee_assignments",
        ["operation_id"],
        unique=False,
    )
    op.create_index(
        "ix_employee_assignments_period",
        "employee_assignments",
        ["employee_id", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_table(
        "employee_authorizations",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("scope_value", sa.String(length=160), nullable=True),
        sa.Column("issued_on", sa.Date(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["authorizations.id"],
            name=op.f("fk_employee_authorizations_authorization_id_authorizations"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_authorizations_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_authorizations")),
    )
    op.create_index(
        op.f("ix_employee_authorizations_employee_id"),
        "employee_authorizations",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_employee_authorizations_expiry",
        "employee_authorizations",
        ["authorization_id", "expires_on"],
        unique=False,
    )
    op.create_table(
        "employee_availability",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_employee_availability_valid_period")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_availability_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_availability")),
    )
    op.create_index(
        "ix_employee_availability_period",
        "employee_availability",
        ["employee_id", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_table(
        "employee_competencies",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("competency_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("assessed_on", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("level >= 0", name=op.f("ck_employee_competencies_nonnegative_level")),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["technical_competencies.id"],
            name=op.f("fk_employee_competencies_competency_id_technical_competencies"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_competencies_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_competencies")),
        sa.UniqueConstraint("employee_id", "competency_id", name="employee_competency"),
    )
    op.create_table(
        "employee_cost_profiles",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("hourly_cost_cents", sa.Integer(), nullable=False),
        sa.Column("travel_cost_cents", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "hourly_cost_cents >= 0", name=op.f("ck_employee_cost_profiles_nonnegative_hourly_cost")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_cost_profiles_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_cost_profiles")),
    )
    op.create_index(
        "ix_employee_cost_profiles_effective",
        "employee_cost_profiles",
        ["employee_id", "effective_from"],
        unique=False,
    )
    op.create_table(
        "employee_operational_restrictions",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("restriction_id", sa.Uuid(), nullable=False),
        sa.Column("scope_value", sa.String(length=160), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_operational_restrictions_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["restriction_id"],
            ["operational_restrictions.id"],
            name=op.f(
                "fk_employee_operational_restrictions_restriction_id_operational_restrictions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_operational_restrictions")),
    )
    op.create_index(
        "ix_employee_restrictions_period",
        "employee_operational_restrictions",
        ["employee_id", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_table(
        "employee_qualifications",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("qualification_id", sa.Uuid(), nullable=False),
        sa.Column("issued_on", sa.Date(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("workload_minutes", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=160), nullable=True),
        sa.Column("external_identifier", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_qualifications_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["qualifications.id"],
            name=op.f("fk_employee_qualifications_qualification_id_qualifications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_qualifications")),
        sa.UniqueConstraint("employee_id", "qualification_id", "issued_on", name="employee_issue"),
    )
    op.create_index(
        op.f("ix_employee_qualifications_employee_id"),
        "employee_qualifications",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_employee_qualifications_expiry",
        "employee_qualifications",
        ["qualification_id", "expires_on"],
        unique=False,
    )
    op.create_table(
        "employee_role_history",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ends_on IS NULL OR ends_on >= starts_on",
            name=op.f("ck_employee_role_history_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_role_history_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_employee_role_history_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_role_history")),
    )
    op.create_index(
        "ix_employee_role_history_period",
        "employee_role_history",
        ["employee_id", "starts_on", "ends_on"],
        unique=False,
    )
    op.create_table(
        "employee_training_plans",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("training_session_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_training_plans_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_employee_training_plans_operation_id_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["training_session_id"],
            ["training_sessions.id"],
            name=op.f("fk_employee_training_plans_training_session_id_training_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_training_plans")),
        sa.UniqueConstraint("employee_id", "training_session_id", name="employee_session"),
    )
    op.create_table(
        "operation_requirements",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("role_demand_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("requirement_type", sa.String(length=48), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_operation_requirements_operation_id_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["role_demand_id"],
            ["operation_role_demands.id"],
            name=op.f("fk_operation_requirements_role_demand_id_operation_role_demands"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_requirements")),
    )
    op.create_index(
        op.f("ix_operation_requirements_operation_id"),
        "operation_requirements",
        ["operation_id"],
        unique=False,
    )
    op.create_table(
        "operation_role_compatible_roles",
        sa.Column("role_demand_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("preference_rank", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_demand_id"],
            ["operation_role_demands.id"],
            name=op.f("fk_operation_role_compatible_roles_role_demand_id_operation_role_demands"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_operation_role_compatible_roles_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_role_compatible_roles")),
        sa.UniqueConstraint("role_demand_id", "role_id", name="demand_compatible_role"),
    )
    op.create_table(
        "requirement_qualification_map",
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("qualification_id", sa.Uuid(), nullable=False),
        sa.Column("minimum_level", sa.String(length=48), nullable=True),
        sa.Column("allows_training", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["qualifications.id"],
            name=op.f("fk_requirement_qualification_map_qualification_id_qualifications"),
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["operation_requirements.id"],
            name=op.f("fk_requirement_qualification_map_requirement_id_operation_requirements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_qualification_map")),
        sa.UniqueConstraint("requirement_id", "qualification_id", name="requirement_qualification"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requirement_qualification_map")
    op.drop_table("operation_role_compatible_roles")
    op.drop_index(
        op.f("ix_operation_requirements_operation_id"), table_name="operation_requirements"
    )
    op.drop_table("operation_requirements")
    op.drop_table("employee_training_plans")
    op.drop_index("ix_employee_role_history_period", table_name="employee_role_history")
    op.drop_table("employee_role_history")
    op.drop_index("ix_employee_qualifications_expiry", table_name="employee_qualifications")
    op.drop_index(
        op.f("ix_employee_qualifications_employee_id"), table_name="employee_qualifications"
    )
    op.drop_table("employee_qualifications")
    op.drop_index("ix_employee_restrictions_period", table_name="employee_operational_restrictions")
    op.drop_table("employee_operational_restrictions")
    op.drop_index("ix_employee_cost_profiles_effective", table_name="employee_cost_profiles")
    op.drop_table("employee_cost_profiles")
    op.drop_table("employee_competencies")
    op.drop_index("ix_employee_availability_period", table_name="employee_availability")
    op.drop_table("employee_availability")
    op.drop_index("ix_employee_authorizations_expiry", table_name="employee_authorizations")
    op.drop_index(
        op.f("ix_employee_authorizations_employee_id"), table_name="employee_authorizations"
    )
    op.drop_table("employee_authorizations")
    op.drop_index("ix_employee_assignments_period", table_name="employee_assignments")
    op.drop_index(op.f("ix_employee_assignments_operation_id"), table_name="employee_assignments")
    op.drop_table("employee_assignments")
    op.drop_index("ix_eligibility_results_classification", table_name="eligibility_results")
    op.drop_table("eligibility_results")
    op.drop_index(
        op.f("ix_decision_training_actions_decision_run_id"), table_name="decision_training_actions"
    )
    op.drop_table("decision_training_actions")
    op.drop_index(
        op.f("ix_decision_assignments_decision_run_id"), table_name="decision_assignments"
    )
    op.drop_table("decision_assignments")
    op.drop_table("training_sessions")
    op.drop_index(op.f("ix_role_aliases_role_id"), table_name="role_aliases")
    op.drop_table("role_aliases")
    op.drop_index(
        op.f("ix_operation_role_demands_operation_id"), table_name="operation_role_demands"
    )
    op.drop_table("operation_role_demands")
    op.drop_index(op.f("ix_employees_name"), table_name="employees")
    op.drop_index("ix_employees_base_active", table_name="employees")
    op.drop_index("ix_employees_active_role", table_name="employees")
    op.drop_table("employees")
    op.drop_table("decision_outcomes")
    op.drop_table("training_catalog")
    op.drop_index("ix_roles_active_family", table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_eligibility_runs_operation_id"), table_name="eligibility_runs")
    op.drop_index(op.f("ix_eligibility_runs_input_hash"), table_name="eligibility_runs")
    op.drop_table("eligibility_runs")
    op.drop_index("ix_decision_runs_operation_created", table_name="decision_runs")
    op.drop_index(op.f("ix_decision_runs_input_snapshot_hash"), table_name="decision_runs")
    op.drop_table("decision_runs")
    op.drop_table("technical_competencies")
    op.drop_table("role_families")
    op.drop_index(op.f("ix_qualifications_category"), table_name="qualifications")
    op.drop_table("qualifications")
    op.drop_index(op.f("ix_operations_status"), table_name="operations")
    op.drop_index("ix_operations_period_status", table_name="operations")
    op.drop_index(op.f("ix_operations_base_location"), table_name="operations")
    op.drop_table("operations")
    op.drop_table("operational_restrictions")
    op.drop_index("ix_calibration_parameters_name_version", table_name="calibration_parameters")
    op.drop_table("calibration_parameters")
    op.drop_table("authorizations")
    op.drop_index("ix_app_users_active_role", table_name="app_users")
    op.drop_table("app_users")
    op.drop_index("ix_audit_events_aggregate", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
